FROM python:3.9

RUN python3 -m pip install --upgrade pip 

# COPY /templates/requirements.txt ./
# RUN pip install -r requirements.txt


COPY {script_name} /{script_name}


ENTRYPOINT ["python3", "/{script_name}"]