FROM python:3.9

RUN python3 -m pip install --upgrade pip 

# COPY /templates/requirements.txt ./
# RUN pip install -r requirements.txt


COPY mapper_example.py /mapper_example.py


ENTRYPOINT ["python3", "/mapper_example.py"]