FROM python:3.9

WORKDIR /

COPY / .

RUN python3 -m pip install --upgrade pip 
RUN pip install protobuf==3.20.1
RUN pip install --no-cache-dir -r requirements.txt


EXPOSE 5000


ENTRYPOINT [ "python3", "./manager.py" ]